export type Ingredient = {
  id: string; name: string; category: string; latin: string; index: number;
  notes: string[]; description: string; compounds: {name:string; note:string; formula:string}[];
};
export const ingredients: Ingredient[] = [
  {id:'strawberry',name:'Strawberry',category:'Fruit',latin:'Fragaria × ananassa',index:0,notes:['Fruity','Floral','Caramel'],description:'Bright, juicy and more complex than its sweetness suggests. A starting point for both delicate and deeply savoury combinations.',compounds:[{name:'Furaneol',note:'Sweet · caramel',formula:'C₆H₈O₃'},{name:'Linalool',note:'Floral · citrus',formula:'C₁₀H₁₈O'},{name:'Hexanal',note:'Green · grassy',formula:'C₆H₁₂O'}]},
  {id:'basil',name:'Basil',category:'Herb',latin:'Ocimum basilicum',index:1,notes:['Herbal','Floral','Spicy'],description:'Fresh green leaves with a floral lift and a gentle, clove-like warmth. Best added late to preserve its delicate aroma.',compounds:[{name:'Linalool',note:'Floral · citrus',formula:'C₁₀H₁₈O'},{name:'Eugenol',note:'Clove · warm',formula:'C₁₀H₁₂O₂'}]},
  {id:'tomato',name:'Tomato',category:'Fruit',latin:'Solanum lycopersicum',index:2,notes:['Green','Fruity','Savoury'],description:'A bridge between fruit and savoury cooking. Ripeness and variety shift the balance of green freshness, sweetness and acidity.',compounds:[{name:'Hexanal',note:'Green · grassy',formula:'C₆H₁₂O'},{name:'Furaneol',note:'Sweet · caramel',formula:'C₆H₈O₃'}]},
  {id:'pepper',name:'Black pepper',category:'Spice',latin:'Piper nigrum',index:3,notes:['Woody','Citrus','Spicy'],description:'Freshly cracked pepper brings citrus and woody aromas as well as heat. A small amount can reshape a familiar ingredient.',compounds:[{name:'Limonene',note:'Citrus · fresh',formula:'C₁₀H₁₆'},{name:'β-Caryophyllene',note:'Woody · spicy',formula:'C₁₅H₂₄'}]},
  {id:'chocolate',name:'Dark chocolate',category:'Pantry',latin:'Theobroma cacao',index:4,notes:['Roasted','Bitter','Floral'],description:'Roasted depth, bitterness and a lingering finish. Cocoa origin and roasting style make each chocolate a different partner.',compounds:[{name:'Phenylacetaldehyde',note:'Honey · floral',formula:'C₈H₈O'},{name:'Trimethylpyrazine',note:'Roasted · nutty',formula:'C₇H₁₀N₂'}]},
  {id:'olive',name:'Olive oil',category:'Pantry',latin:'Olea europaea',index:5,notes:['Green','Grassy','Peppery'],description:'Fresh extra virgin olive oil adds green aroma, rounded texture and a peppery finish. Choose a mild oil for delicate fruit.',compounds:[{name:'Hexanal',note:'Green · grassy',formula:'C₆H₁₂O'},{name:'(E)-2-Hexenal',note:'Green · leafy',formula:'C₆H₁₀O'}]},
  {id:'mushroom',name:'Shiitake',category:'Vegetable',latin:'Lentinula edodes',index:6,notes:['Earthy','Savoury','Woody'],description:'Earthy aroma and savoury depth, with a very different character when raw, roasted or dried. Use its intensity with intention.',compounds:[{name:'1-Octen-3-ol',note:'Earthy · mushroom',formula:'C₈H₁₆O'},{name:'Lenthionine',note:'Sulfurous · savoury',formula:'C₂H₄S₅'}]},
  {id:'lemon',name:'Lemon',category:'Fruit',latin:'Citrus limon',index:7,notes:['Citrus','Floral','Fresh'],description:'The juice brings acidity; the zest brings volatile citrus oils. Treat them as two different tools in the kitchen.',compounds:[{name:'Limonene',note:'Citrus · fresh',formula:'C₁₀H₁₆'},{name:'Linalool',note:'Floral · citrus',formula:'C₁₀H₁₈O'}]},
  {id:'parmesan',name:'Parmesan',category:'Dairy',latin:'Aged hard cheese',index:8,notes:['Savoury','Nutty','Fruity'],description:'Salt, umami and a long, nutty finish. Aged cheese makes a useful counterpoint to sweet fruit and bright acidity.',compounds:[{name:'Butanoic acid',note:'Cheesy · sharp',formula:'C₄H₈O₂'},{name:'Ethyl butanoate',note:'Fruity · sweet',formula:'C₆H₁₂O₂'}]},
];
export type Pairing = {id:string; a:string; b:string; type:'bridge'|'contrast'; novelty:1|2|3; connection:string; why:string; dish:string; method:string};
const rows: [string,string,1|2|3,string,string,string][] = [
 ['strawberry','basil',1,'A floral thread runs through both ingredients. Basil’s green freshness lifts the fruit without covering it.','Strawberry, basil & olive oil','Slice ripe strawberries, add torn basil and a few drops of mild olive oil. Finish with flaky salt just before serving.'],
 ['strawberry','tomato',2,'Sweet, caramel-like and green aroma notes connect these two fruits. Tomato moves strawberry into savoury territory.','Strawberry & tomato gazpacho','Blend two parts ripe tomato with one part strawberry, a splash of sherry vinegar and salt. Chill, then finish with olive oil.'],
 ['strawberry','pepper',2,'Juicy sweetness meets the citrus, wood and gentle heat of freshly cracked pepper. The interest lies in the contrast.','Peppered strawberries on toast','Macerate sliced strawberries with a little sugar for 10 minutes. Spoon onto toasted sourdough and finish with one light turn of black pepper.'],
 ['strawberry','chocolate',1,'Roasted bitterness gives the bright fruit a deeper backdrop. Balance matters more here than a count of shared molecules.','Strawberry & dark chocolate crémeux','Serve a small portion of dark chocolate crémeux with fresh strawberries. Keep the fruit unsweetened to hold onto its acidity.'],
 ['strawberry','olive',2,'Green, grassy notes can connect the fruit and a fresh olive oil. The oil also adds a silky texture that carries aroma.','Strawberry carpaccio, green olive oil','Slice strawberries thinly. Dress with a mild extra virgin olive oil, a few drops of lemon and flaky salt. Serve immediately.'],
 ['strawberry','mushroom',3,'An exploratory meeting of juicy fruit and earthy mushroom. This is a kitchen hypothesis: use roasted shiitake sparingly.','Roasted shiitake with strawberry relish','Roast sliced shiitake until crisp at the edges. Add a small spoon of finely diced strawberry with vinegar and salt. Taste the components together before plating.'],
 ['strawberry','lemon',1,'A floral aroma connection supports a familiar bright combination. Lemon juice adjusts acidity; its zest adds a different aromatic layer.','Fresh strawberry & lemon granita','Macerate strawberries, blend with a little water and sugar, and adjust with lemon juice. Freeze and scrape; add fresh zest to serve.'],
 ['strawberry','parmesan',3,'Sweet acidity meets salt, umami and a nutty finish. Shave the cheese finely so it acts as a seasoning for the fruit.','Strawberry, Parmesan & black pepper','Plate sliced ripe strawberries with a few fine shavings of aged Parmesan. Finish with black pepper and a very small drizzle of olive oil.'],
 ['basil','tomato',1,'Herbal freshness plays against the tomato’s sweet acidity and savoury character. Keep the basil fresh and the tomato at room temperature.','Tomato salad with torn basil','Cut ripe tomatoes, season with salt and rest for 10 minutes. Add torn basil and olive oil just before serving.'],
 ['basil','pepper',2,'Fresh herbal aroma meets woody spice. Use pepper lightly to give the basil definition without overwhelming its floral notes.','Basil & black pepper dressing','Finely chop basil and whisk with olive oil, lemon juice and freshly cracked pepper. Spoon over steamed vegetables.'],
 ['basil','chocolate',3,'Basil’s aromatic freshness cuts through cocoa’s roasted depth. An exploratory combination that works best with a light infusion.','Basil-infused chocolate ganache','Infuse warm cream or oat cream with basil for 10 minutes, strain and use to make a dark chocolate ganache. Taste a small batch first.'],
 ['basil','olive',1,'Green leaf aromas meet a grassy oil. The oil carries the delicate basil notes; blending gently keeps the result fresh.','Fresh basil oil','Briefly blanch basil, cool and dry well. Blend with a mild olive oil and use immediately over vegetables or soup.'],
 ['basil','mushroom',2,'Earthy depth provides a base for basil’s fresh herbal aroma. Add the leaves after cooking so the contrast stays clear.','Seared shiitake with basil','Sear shiitake in a hot pan until golden. Season, remove from the heat, then fold through torn basil.'],
 ['basil','lemon',1,'A shared floral note links basil with lemon zest. Citrus acidity can make the herbal aroma feel especially fresh.','Basil & lemon sorbet','Make a light sugar syrup, cool and briefly infuse with basil. Add lemon juice to taste, strain and churn.'],
 ['basil','parmesan',1,'Nutty, savoury cheese gives fresh basil a rounded foundation. This familiar contrast is the backbone of pesto.','Basil & Parmesan pesto','Crush basil with a small amount of garlic and pine nuts. Fold in finely grated Parmesan and olive oil; adjust with lemon.'],
 ['tomato','pepper',1,'Aromatic pepper adds woody warmth to the tomato’s green, fruity character. Fresh grinding keeps the citrus notes alive.','Slow tomatoes, cracked pepper','Slow-roast tomato halves with olive oil and salt. Finish with fresh pepper after roasting.'],
 ['tomato','chocolate',3,'Cocoa’s bitterness can deepen cooked tomato. This is an exploratory savoury pairing: a little chocolate goes a long way.','Tomato & cocoa braise','Cook down a tomato sauce with onion and smoked chilli. Stir in a small shaving of dark chocolate and taste before adding more.'],
 ['tomato','olive',1,'A shared green aroma provides a natural bridge. The oil softens the perception of acidity and carries the tomato’s aroma.','Tomato water & olive oil','Salt chopped tomatoes and drain through a fine cloth. Serve the clear tomato water cold with a few droplets of fragrant olive oil.'],
 ['tomato','mushroom',1,'Both contribute savoury character, while tomato’s acidity balances the earthy richness of mushrooms.','Roasted tomato & shiitake broth','Roast tomatoes and shiitake, then simmer gently with water. Strain, season and serve with a few fresh tomato pieces.'],
 ['tomato','lemon',2,'Citrus brightness sharpens the tomato’s fruity side. Use zest when the tomato already has enough acidity.','Tomato confit with lemon zest','Slowly cook tomato halves in olive oil. Add a little fresh lemon zest after cooking and serve on toast.'],
 ['tomato','parmesan',1,'Tomato acidity and savoury cheese balance each other. The cheese adds salt and a long, nutty finish.','Tomato risotto, Parmesan crisp','Fold roasted tomatoes into a simple risotto. Finish with Parmesan and serve with a thin baked cheese crisp.'],
 ['pepper','chocolate',2,'Wood and spice bring a new dimension to roasted cocoa. Grind pepper finely and add gradually to avoid a harsh finish.','Black pepper chocolate truffles','Add a small pinch of finely ground pepper to dark chocolate ganache. Chill, shape and coat in cocoa.'],
 ['pepper','olive',1,'The woody aroma of pepper reinforces the peppery finish of some olive oils. Choose a mild oil to keep the balance gentle.','Pepper & olive oil flatbread','Brush warm flatbread with olive oil and finish with freshly cracked pepper and a little flaky salt.'],
 ['pepper','mushroom',1,'Woody spice complements earthy mushroom aroma, while pepper’s heat keeps a rich preparation lively.','Pepper-crusted shiitake','Sear thick slices of shiitake, then finish with cracked pepper and a splash of stock. Reduce briefly and serve.'],
 ['pepper','lemon',1,'Limonene provides a citrus bridge between pepper and lemon zest. Their fresh aromatic notes work alongside pepper’s warmth.','Lemon-pepper finishing salt','Rub finely grated lemon zest into flaky salt. Mix in fresh cracked pepper and use immediately on roast vegetables.'],
 ['pepper','parmesan',1,'A classic balance of spice, salt and nutty richness. Toasting the pepper briefly brings its aroma forward.','Cacio e pepe','Toast cracked pepper gently, add starchy pasta water and toss with pasta. Off the heat, work in finely grated cheese to make a smooth sauce.'],
 ['chocolate','olive',2,'A fruity oil adds texture and fresh green aroma to rich cocoa. Choose an oil with a gentle finish.','Chocolate mousse & olive oil','Serve a small chocolate mousse with a teaspoon of fruity olive oil and a few flakes of salt.'],
 ['chocolate','mushroom',3,'Earthy mushroom and roasted cocoa make an unusual savoury experiment. Keep the cocoa unsweetened and use only a little.','Shiitake with a cocoa jus','Roast shiitake and reduce the pan juices with vegetable stock. Whisk in a pinch of unsweetened cocoa; taste before increasing.'],
 ['chocolate','lemon',2,'A bright citrus accent cuts through cocoa’s richness. Zest gives aroma with less disruption to texture than juice.','Dark chocolate, lemon zest & salt','Spread thin melted chocolate on parchment, add finely grated lemon zest and salt, then chill and break into pieces.'],
 ['chocolate','parmesan',3,'Roasted bitterness meets nutty, salty cheese. An exploratory pairing for tiny portions and careful tasting.','Dark chocolate & Parmesan tasting bite','Serve a small shard of dark chocolate with a paper-thin shaving of Parmesan. Adjust their proportions before building a dish around them.'],
 ['olive','mushroom',1,'Green oil freshens earthy mushrooms while adding texture. Save a little oil to add after cooking.','Warm shiitake, fresh olive oil','Pan-roast shiitake, season with salt and finish off the heat with a drizzle of fresh extra virgin olive oil.'],
 ['olive','lemon',1,'Citrus aroma and acidity brighten the oil’s grassy character. The balance can move from sharp dressing to gentle finishing oil.','Lemon & olive oil dressing','Whisk one part lemon juice with three parts olive oil. Season, then add a little zest if more citrus aroma is needed.'],
 ['olive','parmesan',1,'Grassy aroma, nutty cheese and rounded fat give a simple combination considerable depth.','Parmesan & olive oil toast','Toast sourdough, brush with fragrant olive oil and cover with finely grated Parmesan while still warm.'],
 ['mushroom','lemon',2,'Fresh citrus lifts earthy mushroom aroma. Add it at the end so its brightness remains distinct.','Charred shiitake with lemon','Sear shiitake over high heat. Take off the heat, add a small squeeze of lemon and finish with zest.'],
 ['mushroom','parmesan',1,'Two savoury ingredients build depth together. Parmesan also adds salt and a nutty finish to earthy shiitake.','Shiitake & Parmesan risotto','Fold browned shiitake into risotto. Take off the heat and finish with finely grated Parmesan.'],
 ['lemon','parmesan',1,'Lemon’s brightness keeps aged cheese from feeling heavy. Use zest for aroma and juice only as needed for balance.','Lemon & Parmesan pasta','Toss warm pasta with grated Parmesan, starchy water and lemon zest. Add lemon juice a little at a time, tasting as you go.'],
];
export const pairings: Pairing[] = rows.map(([a,b,novelty,why,dish,method]) => {
  const ai=ingredients.find(i=>i.id===a)!; const bi=ingredients.find(i=>i.id===b)!;
  const shared=ai.compounds.filter(c=>bi.compounds.some(d=>d.name===c.name));
  return {id:[a,b].sort().join(':'),a,b,novelty,type:shared.length?'bridge':'contrast',connection:shared.length?shared[0].name:`${ai.notes[0]} × ${bi.notes[0].toLowerCase()}`,why,dish,method};
});
export const getIngredient=(id:string)=>ingredients.find(i=>i.id===id)!;
export const otherIngredient=(p:Pairing,id:string)=>getIngredient(p.a===id?p.b:p.a);
export const noveltyLabel=(n:number)=>n===1?'Familiar':n===2?'Unexpected':'Exploratory';
export function findPairings(seed:string,type:string,novelty:number,plantOnly=false) {
 return pairings.filter(p=>(p.a===seed||p.b===seed)&&(type==='all'||p.type===type)&&(!plantOnly || (p.a!=='parmesan'&&p.b!=='parmesan'))).sort((a,b)=>Math.abs(a.novelty-novelty)-Math.abs(b.novelty-novelty)||a.id.localeCompare(b.id));
}
